[package]
name = "png_message"
version = "0.1.0"
authors = ["nullxDEADBEEF <andxdgu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
clap = "3.0.0-beta.2"